### ISSUE TITLE
Overlay GPX route during simulation

### ISSUE THREAD

**Issue by TomGC96** [sails-simulator/sailsd#9]
It would be good to be able to upload a GPX route taken from a boat and overlay the actual route, or play it back at the same speed, whilst simulating the ideal boat behaviour. This should use the same parameters for wind direction/speed etc. for comparison with actual performance during a race.

**Comment by kragniz** [comment]
This is a feature that would be easy to implement in [sails-ui-web](https://github.com/sails-simulator/sails-ui-web), since the toolkit used for rendering the map already knows how to handle gpx files (http://openlayers.org/en/latest/apidoc/ol.format.GPX.html). Feel free to reopen the issue over there.
